-- 1. Create Messages Table
create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  name text not null,
  email text not null,
  subject text,
  message text not null,
  status text default 'unread' -- unread, read, replied
);

-- 2. Enable RLS
alter table public.messages enable row level security;

-- 3. Policy: Allow ANYONE (anon) to insert a message
create policy "Allow public to send messages"
on public.messages
for insert
with check ( true );

-- 4. Policy: Allow ADMINs (or authenticated users for now) to view messages
-- For stricter security, you should check for role='admin'
create policy "Allow admins to view messages"
on public.messages
for select
using ( auth.role() = 'authenticated' );
